/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Elisson Novais
 */


import javax.swing.JOptionPane;
public class telabanks extends javax.swing.JFrame {
    

    /**
     * Creates new form telabanks
     */
    public telabanks() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConta = new javax.swing.JLabel();
        txtConta = new javax.swing.JTextField();
        btnExibirMensagem = new javax.swing.JButton();
        lblMensagem = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jMenuBar1 = new javax.swing.JMenuBar();
        txtCadastro = new javax.swing.JMenu();
        ContaCadastro = new javax.swing.JMenuItem();
        Consultinha = new javax.swing.JMenu();
        txtConsulta = new javax.swing.JMenuItem();
        tranzinha = new javax.swing.JMenu();
        txtTransaction = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblConta.setText("Usuario:");

        txtConta.setText("Elisson");
        txtConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContaActionPerformed(evt);
            }
        });

        btnExibirMensagem.setText("Entrar");
        btnExibirMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExibirMensagemActionPerformed(evt);
            }
        });

        lblMensagem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(0, 204, 0));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblCPF.setText("Senha:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/42663f5487eaa411e105f3a0ccf6510a8d2e003f.jpeg"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOGIN");

        txtSenha.setText("12345678");

        txtCadastro.setText("Cliente");

        ContaCadastro.setText("cadastrar usuario");
        ContaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContaCadastroActionPerformed(evt);
            }
        });
        txtCadastro.add(ContaCadastro);

        jMenuBar1.add(txtCadastro);

        Consultinha.setText("Consultar");
        Consultinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultinhaActionPerformed(evt);
            }
        });

        txtConsulta.setText("Consulta");
        txtConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaActionPerformed(evt);
            }
        });
        Consultinha.add(txtConsulta);

        jMenuBar1.add(Consultinha);

        tranzinha.setText("Transação");
        tranzinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tranzinhaActionPerformed(evt);
            }
        });

        txtTransaction.setText("tranferencia");
        txtTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTransactionActionPerformed(evt);
            }
        });
        tranzinha.add(txtTransaction);

        jMenuBar1.add(tranzinha);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtConta, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                            .addComponent(txtSenha)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExibirMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConta)
                    .addComponent(txtConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btnExibirMensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExibirMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExibirMensagemActionPerformed
        // TODO add your handling code here:
        if(txtConta.getText().equals("Elisson")&&txtSenha.getText().equals("12345678")){
           JOptionPane.showMessageDialog(null, "Bem vindo ao portal!");
        }else{
            JOptionPane.showMessageDialog(null, "Acesso Negado!");
        }
        
        
        
        
        
       
        
        
    }//GEN-LAST:event_btnExibirMensagemActionPerformed

    private void ContaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContaCadastroActionPerformed
        ContaCadastro verventana = new ContaCadastro();
        txtCadastro.add(verventana);
        verventana.show();
        
    }//GEN-LAST:event_ContaCadastroActionPerformed

    private void txtConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaActionPerformed
        ContaConsulta verventan = new ContaConsulta();
        Consultinha.add(verventan);
        verventan.show();
    }//GEN-LAST:event_txtConsultaActionPerformed

    private void ConsultinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultinhaActionPerformed

    private void txtTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTransactionActionPerformed
        ContaTransacao trasacion = new ContaTransacao();
        tranzinha.add(trasacion);
        trasacion.show();
    }//GEN-LAST:event_txtTransactionActionPerformed

    private void tranzinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tranzinhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tranzinhaActionPerformed

    private void txtContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telabanks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telabanks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telabanks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telabanks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telabanks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Consultinha;
    private javax.swing.JMenuItem ContaCadastro;
    private javax.swing.JButton btnExibirMensagem;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblConta;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JMenu tranzinha;
    private javax.swing.JMenu txtCadastro;
    private javax.swing.JMenuItem txtConsulta;
    private javax.swing.JTextField txtConta;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JMenuItem txtTransaction;
    // End of variables declaration//GEN-END:variables

    private static class Project_javazinho {

        public Project_javazinho() {
        }
    }
}
